// Code generated by "string2enum -samepkg -linecomment -type SectionType"; DO NOT EDIT.

package mapfile

import "fmt"

// SectionTypeFromString returns the SectionType enum corresponding to s.
func SectionTypeFromString(s string) SectionType {
	if len(s) == 0 {
		return 0
	}
	for i := range _SectionType_index[:len(_SectionType_index)-1] {
		if s == _SectionType_name[_SectionType_index[i]:_SectionType_index[i+1]] {
			return SectionType(i + 1)
		}
	}
	panic(fmt.Errorf("unable to locate SectionType enum corresponding to %q", s))
}

func _(s string) {
	// Check for duplicate string values in type "SectionType".
	switch s {
	// 1
	case "CODE":
	// 2
	case "DATA":
	}
}
