// Code generated by "stringer -linecomment -type SectionType"; DO NOT EDIT.

package mapfile

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SectionTypeCode-1]
	_ = x[SectionTypeData-2]
}

const _SectionType_name = "CODEDATA"

var _SectionType_index = [...]uint8{0, 4, 8}

func (i SectionType) String() string {
	i -= 1
	if i >= SectionType(len(_SectionType_index)-1) {
		return "SectionType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SectionType_name[_SectionType_index[i]:_SectionType_index[i+1]]
}
